[package]
name = "zk-implementation"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
ark-ff = "0.5.0"
ark-bn254 = "0.5.0"
ark-std = "0.5.0"
sha3 = "0.10.8"
field-tracker = { git = "https://github.com/sublinearlabs/field-tracker" }
